from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from .schema import SchemaClass


class IRISRuntimeProtocol(Protocol):
    """Protocol defining the interface for IRIS runtime backends."""

    def load_schema(self, classname: str) -> dict[str, Any] | None: ...
    def list_classes(self, pattern: str) -> list[str]: ...
    def replace_class(self, schema_class: "SchemaClass") -> None: ...
    def save_object(self, classname: str, data: dict[str, Any], obj_id: Any | None = None) -> Any: ...
    def open_object(self, classname: str, obj_id: Any) -> dict[str, Any] | None: ...
    def open_native_object(self, classname: str, obj_id: Any) -> Any | None: ...
    def cls(self, classname: str) -> Any: ...
    def native_class(self, classname: str) -> Any: ...
    def delete_object(self, classname: str, obj_id: Any) -> None: ...
    def query_rows(
        self,
        classname: str,
        fields: list[str],
        filters: dict[str, Any],
        order_by: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[dict[str, Any]]: ...
    def sql(self, statement: str, params: list[Any] | None = None) -> list[tuple[Any, ...]]: ...
    def compile(self, classname: str) -> None: ...
    def looks_like_iris_object(self, value: Any) -> bool: ...
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
