"""
.pyi stub file generator for IDE support.

Usage:
    python -m iris_orm.stubs Demo.Test ./src/python/
"""
from __future__ import annotations

from pathlib import Path


def generate_stub(classname: str) -> str:
    """
    Generate a .pyi stub for the given IRIS classname.

    Queries IRIS properties via introspection (Plan A style) and also
    checks the _MODEL_REGISTRY for relationship definitions.
    """
    from .introspection import get_class_properties
    from .metaclass import _MODEL_REGISTRY
    from .types import iris_type_to_annotation

    # Gather properties
    try:
        props = get_class_properties(classname)
    except Exception:
        props = []

    # Gather relationship defs from registered model (if any)
    registered = _MODEL_REGISTRY.get(classname)
    rel_defs = getattr(registered, "_iris_rel_defs", {})

    # Build imports
    needs_datetime = any(
        ann in (
            "Optional[datetime.date]",
            "Optional[datetime.time]",
            "Optional[datetime.datetime]",
        )
        for p in props
        for ann in [iris_type_to_annotation(p.iris_type)]
    )

    lines: list[str] = [
        "# auto-generated by iris_orm.stubs — do not edit by hand",
        "from __future__ import annotations",
        "",
        "from typing import Any, ClassVar, Iterator, Optional",
        "",
    ]
    if needs_datetime:
        lines.append("import datetime")
        lines.append("")

    lines += [
        "from iris_orm import IRISQuerySet",
        "from iris_orm.descriptors import IRISRelationshipManager",
        "",
        "",
        f"class {classname.split('.')[-1]}:",
        f'    _iris_classname: ClassVar[str] = "{classname}"',
        "    objects: ClassVar[IRISQuerySet]",
        "",
    ]

    # Property stubs
    for prop in props:
        annotation = iris_type_to_annotation(prop.iris_type)
        lines.append(f"    @property")
        lines.append(f"    def {prop.name}(self) -> {annotation}: ...")
        lines.append(f"    @{prop.name}.setter")
        lines.append(f"    def {prop.name}(self, value: {annotation}) -> None: ...")
        lines.append("")

    # Relationship stubs
    for rel_name, rd in rel_defs.items():
        related_short = rd.related_classname.split(".")[-1]
        if rd.cardinality in ("parent", "one"):
            ret_type = f"Optional[{related_short}]"
        else:
            ret_type = "IRISRelationshipManager"
        lines.append(f"    @property")
        lines.append(f"    def {rel_name}(self) -> {ret_type}: ...")
        lines.append("")

    # CRUD stubs
    lines += [
        "    @property",
        "    def pk(self) -> Optional[str]: ...",
        "",
        "    def save(self) -> None: ...",
        "    def delete(self) -> None: ...",
        "",
        "    @classmethod",
        f"    def get(cls, obj_id: Any) -> Optional[{classname.split('.')[-1]}]: ...",
        "",
        "    @classmethod",
        f"    def create(cls, **kwargs: Any) -> {classname.split('.')[-1]}: ...",
        "",
    ]

    return "\n".join(lines)


def write_stub(classname: str, output_root: str) -> Path:
    """
    Write the generated .pyi stub to disk.

    "Demo.Test" → <output_root>/Demo/Test.pyi
    Returns the Path that was written.
    """
    source = generate_stub(classname)
    parts = classname.split(".")
    rel_path = Path(*parts[:-1], parts[-1] + ".pyi") if len(parts) > 1 else Path(parts[0] + ".pyi")
    output_path = Path(output_root) / rel_path
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding="utf-8")
    return output_path


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse
    import importlib
    import sys

    parser = argparse.ArgumentParser(
        description="Generate a .pyi stub for an IRIS ORM model.",
    )
    parser.add_argument(
        "iris_classname",
        help="IRIS class name, e.g. Demo.Test",
    )
    parser.add_argument(
        "output_root",
        help="Directory root to write the .pyi file into.",
    )
    parser.add_argument(
        "--module",
        default=None,
        help="Python module to import before generating the stub.",
    )
    args = parser.parse_args()

    if args.module:
        importlib.import_module(args.module)

    path = write_stub(args.iris_classname, args.output_root)
    print(f"Written: {path}")


if __name__ == "__main__":
    main()
