"""
.pyi stub generator for IRIS persistent classes.

Usage::

    python -m iris_orm.stubs <IRISClassName> <output_root>

Example::

    python -m iris_orm.stubs Demo.Test ./src/python/
    # writes ./src/python/Demo/Test.pyi

The generated stub contains typed ``@property`` declarations for every
persistent property so that IDEs (PyCharm, VS Code + Pylance) provide
accurate auto-completion and type checking without executing any IRIS code.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from .introspection import PropertyInfo, get_class_properties
from .types import iris_type_to_annotation


# ---------------------------------------------------------------------------
# Stub template helpers
# ---------------------------------------------------------------------------

_HEADER = '''\
# This file is auto-generated by iris_orm.stubs — DO NOT EDIT.
# Re-generate with:  python -m iris_orm.stubs {classname} <output_root>
from __future__ import annotations

import datetime
from typing import Any, Optional, Iterator, ClassVar, overload

from iris_orm import IRISModel, IRISQuerySet

'''


def _property_lines(prop: PropertyInfo) -> list[str]:
    annotation = iris_type_to_annotation(prop.iris_type)
    lines = [
        f"    @property",
        f"    def {prop.name}(self) -> {annotation}: ...",
        f"    @{prop.name}.setter",
        f"    def {prop.name}(self, value: {annotation}) -> None: ...",
        "",
    ]
    return lines


def generate_stub(classname: str) -> str:
    """Return the full text of a ``.pyi`` stub for *classname*."""
    try:
        properties = get_class_properties(classname)
    except Exception as exc:
        print(f"[iris_orm.stubs] Warning: could not introspect {classname!r}: {exc}", file=sys.stderr)
        properties = []

    parts: list[str] = [_HEADER.format(classname=classname)]

    # class declaration
    # Convert "Demo.Test" → "Test" for the Python class name.
    py_class = classname.split(".")[-1]
    parts.append(f"class {py_class}(IRISModel):")
    parts.append(f"    _iris_classname: ClassVar[str]")
    parts.append(f"    objects: ClassVar[IRISQuerySet]")
    parts.append("")

    if not properties:
        parts.append("    ...")
        parts.append("")
    else:
        for prop in properties:
            parts.extend(_property_lines(prop))

    # CRUD stubs
    parts += [
        "    @property",
        "    def pk(self) -> Optional[str]: ...",
        "    def save(self) -> None: ...",
        "    def delete(self) -> None: ...",
        "    @classmethod",
        f"    def get(cls, obj_id: str) -> Optional[{py_class}]: ...",
        "    @classmethod",
        f"    def create(cls, **kwargs: Any) -> {py_class}: ...",
        "",
    ]

    # objects queryset stub
    parts += [
        "class _Manager:",
        f"    def all(self) -> IRISQuerySet: ...",
        f"    def filter(self, **kwargs: Any) -> IRISQuerySet: ...",
        f"    def first(self) -> Optional[{py_class}]: ...",
        f"    def count(self) -> int: ...",
        f"    def __iter__(self) -> Iterator[{py_class}]: ...",
        "",
    ]

    return "\n".join(parts)


def write_stub(classname: str, output_root: str) -> Path:
    """Generate and write a ``.pyi`` stub, returning the path written."""
    stub_text = generate_stub(classname)

    # "Demo.Test" → output_root/Demo/Test.pyi
    parts = classname.split(".")
    out_path = Path(output_root).joinpath(*parts).with_suffix(".pyi")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(stub_text, encoding="utf-8")
    return out_path


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="python -m iris_orm.stubs",
        description="Generate .pyi stubs for an IRIS persistent class.",
    )
    parser.add_argument("classname", help='IRIS class name, e.g. "Demo.Test"')
    parser.add_argument(
        "output_root",
        nargs="?",
        default=".",
        help="Root directory for output (default: current directory)",
    )
    args = parser.parse_args(argv)

    out_path = write_stub(args.classname, args.output_root)
    print(f"Stub written → {out_path}")


if __name__ == "__main__":
    main()
